### ISSUE TITLE
Just an info... Exist the ETA...

### ISSUE THREAD

**Issue by FirenzeIT** [Timmeey86/FS25_UnloadBalesEarly#1]
Hello @Timmeey86 , is there any ETA for you to use this mod?? i tried it but it doesn't work..

**Comment by Timmeey86** [comment]
Hi, I'm currently waiting for a response of the author of the same mod for FS19.
Unfortunately it seems like a lot more work is required to get this done for FS22 then compared to FS19, too, so I'm afraid I'll focus on my other mods first

**Comment by FirenzeIT** [comment]
Ah ok, it's Mogli12 right? I have also write him here on github, for have a
chance for convert it for FS22.. It's very hard to make a new one or
convert it (i tried for my self to convert with Giants editor, but without
luck).. However, i only write my feedback and ask for eventually ETA, take your time, not worries 👍🏻 

Il Sab 17 Feb 2024, 06:20 Timmeey86 ***@***.***> ha scritto:

**Comment by Timmeey86** [comment]
@FirenzeIT I got a first version which works for round and square balers, but not for baler-wrappers yet

**Comment by FirenzeIT** [comment]
> @FirenzeIT I got a first version which works for round and square balers, but not for baler-wrappers yet

Wow, now i testing it, so for now, balers with wrappers function not works yet, right?? I testing without wrappers functions...

**Comment by Timmeey86** [comment]
This is just a first version to get really anything working.

Square balers work well, round balers are ok, but unloading round bales is a bit buggy because they start small and then suddenly get big.
You can unload with at least 500 liters, and for some balers you need to turn off the baler before you can unload with the Y key

**Comment by FirenzeIT** [comment]
> This is just a first version to get really anything working.
> 
> Square balers work well, round balers are ok, but unloading round bales is a bit buggy because they start small and then suddenly get big. You can unload with at least 500 liters, and for some balers you need to turn off the baler before you can unload with the Y key

Hi, i tried with 2 baler wrappers and not works the unloading system (over 7000 lt).. Now i trying without wrappers system...

![20240222050235_1](https://github.com/Timmeey86/FS22_UnloadBalesEarly/assets/113168067/70d8c260-e77c-4fa1-a042-88420bc50b6c)

**Comment by Timmeey86** [comment]
Yes, it does not work for baler wrappers yet

**Comment by FirenzeIT** [comment]
Yes, i tested it, but without wrapper system (only baler) it's possible
unload a bale, wow 🤩. I wait for extended to wrappers baler too (i'm
excited) 😁 it's a very very useful mod for have FS22 more realistic and
functionally 😎😎

Il Gio 22 Feb 2024, 15:46 Timmeey86 ***@***.***> ha scritto:

**Comment by Timmeey86** [comment]
It works for baler/wrapper combos as well now. It is a bit buggy, for example the bale might spawn under the baler, and it will not wrap the bale.
Fixing that will take time

**Comment by Timmeey86** [comment]
unloading should now work properly with baler/wrapper combos and also cotton harvesters

**Comment by Timmeey86** [comment]
You can now also configure the unloading threshold, and a first release candidate has been created: https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases

**Comment by FirenzeIT** [comment]
> You can now also configure the unloading threshold, and a first release candidate has been created: https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases

Hi, i just tried last and pre-last version, why u choose to stop motor on baler (for square bales) instead with motor on?? With motor on, my personal opinion, it's more realistic than motor off of the baler.. 

Another problem: i have a warnings with the mod:
**_2024-02-27 19:16   Warning: FS22_UnloadBalesEarly: Could not read settings_**

Add below also a complete log.

[log.txt](https://github.com/Timmeey86/FS22_UnloadBalesEarly/files/14424302/log.txt)

For the rest, it's works very well with all type of balers, nice job!!!

**Comment by Timmeey86** [comment]
The logic for unloading balers fully unloads the bale from the baler, and for square balers you need to turn them off in base game in order to "push" the finished bale(s) out. I can try and see if I can get it to work with an active baler, but I'm not sure if I can.

I could not reproduce the log message, but I made a new commit which has more detailed logging than before. Can you load the game with the newest `main` branch and send me the log again, please?

**Comment by FirenzeIT** [comment]
> The logic for unloading balers fully unloads the bale from the baler, and for square balers you need to turn them off in base game in order to "push" the finished bale(s) out. I can try and see if I can get it to work with an active baler, but I'm not sure if I can.
> 
> I could not reproduce the log message, but I made a new commit which has more detailed logging than before. Can you load the game with the newest `main` branch and send me the log again, please?

I just tried also this version and now i have 2 warnings in the log.

2024-02-27 20:53   Warning: FS22_UnloadBalesEarly: Could not get path to UnloadBalesEarly.xml settings file since the savegame directory is nil.
2024-02-27 20:53   Warning: FS22_UnloadBalesEarly: Could not restore settings.

[log.txt](https://github.com/Timmeey86/FS22_UnloadBalesEarly/files/14426174/log.txt)

EDIT: Now not works anymore, i have more than 33/35% but nothing appear in F1 and not on settings in-game... :/ (but it's reported work 2024-02-27 23:04 FS22_UnloadBalesEarly: Forcing early unload possibility for balerWrapper Fendt 'rotana180')

[log#2.txt](https://github.com/Timmeey86/FS22_UnloadBalesEarly/files/14426343/log.2.txt)

![20240227232043_1](https://github.com/Timmeey86/FS22_UnloadBalesEarly/assets/113168067/f5f1dbcf-2d98-48a3-984f-f0c92ab22d94)

**Comment by Timmeey86** [comment]
You can ignore the warnings, they will only appear when you create a new game. If you save once and then load again, the warnings won't be there.

The reason that unloading no longer works is probably because some mod you are using causes the second bar from the bottom to be at 35% while the bottom bar is at 0%. Usually, a baler only has one fill unit:
![image](https://github.com/Timmeey86/FS22_UnloadBalesEarly/assets/10223149/21a5be91-9380-4fb6-b8f9-a89461249713)

Do you know which mod causes the fill bar to be split into two?

**Comment by FirenzeIT** [comment]
> You can ignore the warnings, they will only appear when you create a new game. If you save once and then load again, the warnings won't be there.
> 
> The reason that unloading no longer works is probably because some mod you are using causes the second bar from the bottom to be at 35% while the bottom bar is at 0%. Usually, a baler only has one fill unit: ![image](https://private-user-images.githubusercontent.com/10223149/308735141-21a5be91-9380-4fb6-b8f9-a89461249713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjUxNDgsIm5iZiI6MTcwOTIyNDg0OCwicGF0aCI6Ii8xMDIyMzE0OS8zMDg3MzUxNDEtMjFhNWJlOTEtOTM4MC00ZmI2LWI4ZjktYTg5NDYxMjQ5NzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE2NDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwY2RhN2RkMTliODA1ZDRmNThlN2M0ZDA2OTIwNzM4Yjk5YTMyZWZmOWE1YWViNjY4MGVjYmFjZmMwYjYwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QfkD6SZ2JQQzS3gEhJDg-RhA3g1u1ROPUPHKPgbO1zY)
> 
> Do you know which mod causes the fill bar to be split into two?

Hi, the mod with 2 chambers (pre-chamber) is the Fendt Rotana 180 Xtra-V (external mod on kingmods) [The Fendt Rotana 180 Xtra-V sets new standards in baler technology. With its additional pre-chamber, it enables continuous baling without you having to stop. This saves you valuable time and increases your efficiency], where you can have 2 bales (one finished, in the wrapper, and the other still to be finished), so when the last one is unloaded, the one still to be finished obviously stays in.

**Second question:** I have a debug message concerning the use of a default packer:
2024-02-29 05:16 FS22_UnloadBalesEarly: Forcing early unload possibility for balerWrapper PÖTTINGER 'impress185VCPro'
2024-02-29 05:16 DEBUG: balerWrapper PÖTTINGER impress185VCPro has overloadingStartFillLevelPct 1

What does this mean? Is this normal?

**Comment by Timmeey86** [comment]
Whoops, the debug message was not supposed to end up on GitHub ;) I'm experimenting with overloading the first chamber of a cotton harvester to the second chamber early. Maybe that baler mod works the same, I'll have to look into it

**Comment by FirenzeIT** [comment]
> Whoops, the debug message was not supposed to end up on GitHub ;) I'm experimenting with overloading the first chamber of a cotton harvester to the second chamber early. Maybe that baler mod works the same, I'll have to look into it

Ah ok 👍🏻 Yes, possible which works the same as normal balers (all default's baler have this type of message).. But your mod it's very very useful (as other's two: Conservation Agriculture and Trees Value Info, both with 5* on modhub) 👍🏻 

PS. so this message, it's not an error right? Only information about this and nothing else..

**Comment by Timmeey86** [comment]
Glad you are enjoying it. I just uploaded a new zip file:

- Two-chamber balers are supported now (press once to overload the buffer, then press again to unload the bale)
- There should be no more warnings or debug log messages now

https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases/tag/v0.1.1.0

**Comment by FirenzeIT** [comment]
> Glad you are enjoying it. I just uploaded a new zip file:
> 
> * Two-chamber balers are supported now (press once to overload the buffer, then press again to unload the bale)
> * There should be no more warnings or debug log messages now
> 
> https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases/tag/v0.1.1.0

Hello Bro, with this update you hit the nail on the head; I have re-tested the baler above (with the second chamber, Fendt Rotana 180 Xtra-V) and everything works perfectly.. Wow, 100++!! Great job! No errors or bugs or any other type of warnings; for example if I select the 180 bale to be wrapped, it comes out as 180 as big (while the actual measurements in litres remain as they are collected).. Therefore, at least so far, the mod is stable and everything works.. All this tested with round bales/balers, as soon as I can I also test the square ones (e.g. with the Hesston 4900) 👍🏻 

**_EDIT:_** I have also tried the Krone for square bales (the one that includes the silage additive), and 2 other poettinger and fendt, everything works great, at the moment I have not experienced any problems with these balers either. If possible, let's keep this thread open for a short time, so at least I have a chance to testing more deeply....

**Comment by Timmeey86** [comment]
@FirenzeIT I created a new release since the version you have has problems with base game balers when there is only one fill type for a baler:

https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases/tag/v1.0.0.0

This version will also be submitted to mod hub

**Comment by FirenzeIT** [comment]
> @FirenzeIT I created a new release since the version you have has problems with base game balers when there is only one fill type for a baler:
> 
> https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases/tag/v1.0.0.0
> 
> This version will also be submitted to mod hub

Hi Bro, yes i just downloaded and use a modhub version (obv here i download the updates 👍🏻), works very well, also an update of TreesValueInfo, thank you very much.
