### ISSUE TITLE
ERROR: Failed to create bale

### ISSUE THREAD

**Issue by FearlessNite345** [Timmeey86/FS25_UnloadBalesEarly#12]
So i have been unable to use this as any time i click O it just does the animation like its unloading a bale but nothing get unloaded it just throws a console error of "Failed to create bale" i understand the struggle currently as there's no docs i have issues with my scripts to just wanted to report so you are aware

**Comment by Timmeey86** [comment]
Hi, which version were you using?
Also single player or multiplayer? 
Which baler?
If possible, also upload your log file

**Comment by FearlessNite345** [comment]
1.0.0.0
Multiplayer
The john deere one with the wrapper on it not sure of the model as im not able to check right now
Will need to get the error again for log file once i have time

**Comment by Timmeey86** [comment]
yeah multiplayer doesn't work in 1.0.0.0

The current main branch fixes most issues but there is still one issue where some client players don't get the unload option. 

If you want to, you can try with that version, but you'll have to create a zip yourself, I'll not at home right now unfortunately

**Comment by Timmeey86** [comment]
This should be fixed in the most recent ModHub update: https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=303420
