### ISSUE TITLE
Bug: no settings

### ISSUE THREAD

**Issue by alzhur** [Timmeey86/FS25_UnloadBalesEarly#14]
Mod version 1.0.0.1, game version 1.3.0.0, singleplayer.
No option to configure unload threshold in settings.

PS Thanks for adding "overload from buffer" functionality to your mod, no hassle for me updating my mod for this for fs25.
PPS Feature request: add option to disable all mangling with "unload unfinished bale" functionality, leaving only overload function active.

**Comment by Timmeey86** [comment]
That's not a bug, that's a feature I disabled for FS25 because there was too little developer documentation for adding settings.
We have now found a way, so I will start implementing this, it might take a while, though. 

For the time being, you can change the `state="1"` value in the FS25_UnloadBalesEarly.xml where 
```txt
1 = 0%
2 = 10%
3 = 25%
4 = 33%
5 = 50%
6 = 66%
7 = 75%
8 = 90%
```

Obviously you need to change that while the game is not running.

**Comment by alzhur** [comment]
So, it's just not implemented currently for FS25.
Ok.
And what you think about adding `state="default"`, for only overload enabled mode?
Or, maybe, change this from global setting to per-device?

**Comment by Timmeey86** [comment]
This version will allow you to set thresholds for overloading and unloading separately, and you can change the keybind, too, if you want to.
If you set one of the thresholds to "-", the feature will be disabled, so you can choose to only allow overloading or only allow unloading


[FS25_UnloadBalesEarly.zip](https://github.com/user-attachments/files/18047825/FS25_UnloadBalesEarly.zip)

**Comment by alzhur** [comment]
Thanks for quick release!
With this new version 1.1.0.0 two new options became available in settings menu.
But second option (unload unfinished bale) works not the way I think it should when set to "--" (unloadingThreshold state="-1").
Currently - machine can not unload unfinished bale at all.
My assumption - machine should function as no mod installed.
Tested on vanilla cotton harvester JD CP960, which can unload unfinished bale at >25% fill level by default.
But with unloadingThreshold state="-1" it can not do that at all.
For overloadingThreshold state="-1" it's not a problem, there is no such function in vanilla game.

**Comment by alzhur** [comment]
Something like this: save default value of  `spec.unfinishedBaleThreshold` and return it back if `UnloadBalesEarly.settings.unloadingThreshold` is nil.
```
function EarlyUnloadHandler.getCanUnloadUnfinishedBale(baler, superFunc)
	-- Adjust the threshold now. This will also adjust it for functions which don't use the getter
	local spec = baler.spec_baler
	spec.unfinishedBaleThreshold_default = spec.unfinishedBaleThreshold
	spec.unfinishedBaleThreshold = EarlyUnloadHandler.getUnloadBaleThreshold(baler, 1)
	traceMethod(("getCanUnloadUnfinishedBale/fillLevel = %s, threshold = %s"):format(baler:getFillUnitFillLevel(spec.fillUnitIndex), spec.unfinishedBaleThreshold))
	-- Return the base game implementation now that we adjusted the threshold
	return superFunc(baler)
end


function EarlyUnloadHandler.getUnloadBaleThreshold(baler, fillUnitIndex)
	local spec = baler.spec_baler
	local factor = 1
	if UnloadBalesEarly.settings.unloadingThreshold then
		factor = UnloadBalesEarly.settings.unloadingThreshold / 100
	else
		factor = spec.unfinishedBaleThreshold_default / baler:getFillUnitCapacity(fillUnitIndex)
	end
	return baler:getFillUnitCapacity(fillUnitIndex) * factor
end
```
Also, in function EarlyUnloadHandler.getCanUnloadUnfinishedBale, you presume what for device with multiple fill units, main chamber is always fill unit №1. Isn't this is too wild?

**Comment by Timmeey86** [comment]
[FS25_UnloadBalesEarly.zip](https://github.com/user-attachments/files/18048514/FS25_UnloadBalesEarly.zip)

This version should now provide base game behavior when the mod functions are turned off.
Note that by default, the JD cotton harvester always allows unloading early, but with only base game mechanics, you cannot overload before 25% total bale volume.

Therefore, if you overload early with my mod, you will also be able to unload earlier.

Concerning the fill index 1 for bale chambers: I currently do not know of any reliable way of detecting which bale chamber is the main one. In FS22 it looked like all modhub balers used chamber 1 for the bale chamber, not sure if the game even allows otherwise.

**Comment by alzhur** [comment]
Thanks, now it's working as it should (IMHO)!
Do not forget to change help message to reflect this change.

About fill units:
1. Exclude all fill units referenced in `<motorized>-<consumerConfigurations>` (or all with fill type of diesel or def).
2. Exclude fill unit referenced in `<baler>-<buffer>`.
In rare case that more than one unit remains after that - I do not know how to detect which one is main. =(

PS Bonus - Russian localization for new strings. 
[locale_ru.xml.txt](https://github.com/user-attachments/files/18048678/locale_ru.xml.txt)
Edit:
PPS Default value for spec_baler.unfinishedBaleThreshold is 2000, and with your mod it can be set to lower value (depends on volume of main fill unit). For JD one, as example, 1000 (at 10%) or 0.

**Comment by alzhur** [comment]
Do you plan to release this version at modhub?

**Comment by Timmeey86** [comment]
I can only submit a new version every four weeks, so there likely won't be a ModHub update until end of January since Giants will do a Christmas break
