### ISSUE TITLE
RU translation

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS25_UnloadBalesEarly#18]
@vitalii2011 
Добрый день!

I've added two UI settings and four new texts to my mod. It would be nice if you could translate them:

https://github.com/Timmeey86/FS25_UnloadBalesEarly/blob/main/i18n/locale_ru.xml

**Comment by alzhur** [comment]
My variant:
[locale_ru.xml.txt](https://github.com/user-attachments/files/18048678/locale_ru.xml.txt)
