### ISSUE TITLE
Not an issue - Contributing Translations

### ISSUE THREAD

**Issue by Ferchu425** [Timmeey86/FS25_UnloadBalesEarly#7]
Hi there, I'd like to contribute with the spanish translations, two versions, traditional spanish ("es") and latin american spanish ("ea" seems to be the code)

Im attaching a TXT file with everything, hope it's complete, I just left out the "Changelog" 

[translations.txt](https://github.com/Timmeey86/FS22_UnloadBalesEarly/files/15311956/translations.txt)

Hope it helps and keep up with the great work

**Comment by Timmeey86** [comment]
Thanks for your contribution! I added the translations to the main branch and created a new release. Can you confirm this zip file works properly with spanish localization? (I haven't tested it yet)

https://github.com/Timmeey86/FS22_UnloadBalesEarly/releases/tag/v1.0.0.2

**Comment by Ferchu425** [comment]
Hi, glad you liked it! Unfortunately you have an XML error, an extra "<" on line 82 at the end.

Also, I dont understand why, the description doesnt appear in spanish in the download center

**Comment by Timmeey86** [comment]
Thanks for pointing that out. I fixed the XML error and replaced the ZIP file in the release (just download it again).

I also removed the Spanish `<description>` since apparently the mod hub will only ever display German, French or English descriptions and default to English for any other language.

Additional languages are apparently only supported within the game itself (settings, help menu, input bindings etc)🙁

**Comment by Timmeey86** [comment]
Just to confirm, I tried the [Fields of La Mancha map](https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=245814&title=fs2022) which has a Spanish description, and indeed, only the English text is displayed in the ingame mod hub after setting my client to Spanish

**Comment by Ferchu425** [comment]
Ok, I can confirm that translations looks OK

**Comment by FirenzeIT** [comment]
Hi @Timmeey86, i have also a full translation for IT (Italian language), please add this too in a next and future updates (here and modhub), thank you. 👍🏻 

[IT_translation.txt](https://github.com/Timmeey86/FS22_UnloadBalesEarly/files/15447541/IT_translation.txt)
