### ISSUE TITLE
Baller wont start after empty early 

### ISSUE THREAD

**Issue by Napoleon231187** [Timmeey86/FS25_UnloadBalesEarly#8]
I have encounter the following issue 

I played this game on multiplayer and fished one of my contracts jobs @ 99% i clicked on O and everything got out apart what was left in the chamber about 1400l on a 240cm setting  the only way to get it was with Y what also shown like on O the option to empty everything.  after that the baler refuse to start no matter how many time or how hard i was hitting B :-p 
The first thing i have done is restart the game and when i loaded back in the game the 1400l was back inside the machine and the baler was able to start but it would turn off straight away 

I used the krone baler with collector.
it start working again  after resetting the baler via the map and teleport it back to the shop  

not sure if it is user error or there is a problem :-?

thx for any help

**Comment by Timmeey86** [comment]
Hi, thanks for reporting this. Right now we script modders are unfortunately a bit in the dark since there is zero documentation on the FS25 scripting API yet.

I'm not even sure I can do anything about this issue right now, but I'll try and see if I can reproduce it or figure out something. It's just a lot of trial&error and guessing so don't expect any quick fix

**Comment by Napoleon231187** [comment]
Is not game breaking so don’t worry 😉 it can be fixed by resetting.Next time it happens I will film it Sent from my iPhoneOn 16 Nov 2024, at 09:31, Timmeey86 ***@***.***> wrote:﻿
Hi, thanks for reporting this. Right now we script modders are unfortunately a bit in the dark since there is zero documentation on the FS25 scripting API yet.
I'm not even sure I can do anything about this issue right now, but I'll try and see if I can reproduce it or figure out something. It's just a lot of trial&error and guessing so don't expect any quick fix

**Comment by Timmeey86** [comment]
I have prepared a release which should fix at least most of the issues. Please test and report if it works for you.
Note that in this version, the bale will be very small while unloading and then suddenly get a lot bigger if you are a multiplayer client. It will look normal in single player and for the multiplayer host. That should however only be a visual thing and not impact the functionality.

https://github.com/Timmeey86/FS25_UnloadBalesEarly/releases/tag/FS25_1.0.0.1

**Comment by Napoleon231187** [comment]
Thx so much I will give it a go tomorrow:-)Sent from my iPhoneOn 20 Nov 2024, at 21:54, Timmeey86 ***@***.***> wrote:﻿
I have prepared a release which should fix at least most of the issues. Please test and report if it works for you.
Note that in this version, the bale will be very small while unloading and then suddenly get a lot bigger if you are a multiplayer client. It will look normal in single player and for the multiplayer host. That should however only be a visual thing and not impact the functionality.
https://github.com/Timmeey86/FS25_UnloadBalesEarly/releases/tag/FS25_1.0.0.1

**Comment by Timmeey86** [comment]
Multiplayer should now work properly with the most recent ModHub update: 
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=303420

**Comment by Napoleon231187** [comment]
Thx so much 🙃Sent from my iPhoneOn 5 Dec 2024, at 15:02, Timmeey86 ***@***.***> wrote:﻿
Multiplayer should now work properly with the most recent ModHub update:
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=303420
